### ISSUE TITLE
Factory Error 500 during upgrade 1.10.7 -> 1.11.0

### ISSUE THREAD

**Issue by VonNao** [siderolabs/talos#11720]
## Bug Report

We tried upgrading our nodes 1.11.0. we got the following error from the factory.talos.dev "Internal Server Error" 500

### Description
Our Images use the following semantic ID. My guess would be that vmware tools are the problem. Last time we faced the same error was during the upgrade from 1.9.0 to 1.10.0. If i remember correct it was the change to the universal installer on broadcoms side. 

903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40

Following the old Issue
Update: #10372

### Environment

- Talos version: 1.10.7
- Kubernetes version: 1.33.4
- Platform: Vmware

**Comment by smira** [comment]
Yes, that's an issue, we'll get it fixed in the next release (1.11.1), thanks for reporting it.

**Comment by smira** [comment]
This should be resolved with backporting a change https://github.com/siderolabs/extensions/pull/801, which is anyways planned to be backported, so I'm going to close this issue for now.

**Comment by rouke-broersma** [comment]
@smira I see this is closed but this is not fixed until talos 1.11.1 comes out, is that correct? So if we need vmtoolsd we can't upgrade yet?

**Comment by smira** [comment]
> [@smira](https://github.com/smira) I see this is closed but this is not fixed until talos 1.11.1 comes out, is that correct? So if we need vmtoolsd we can't upgrade yet?

yes, we can't fix extensions after they are released, the next release will fix it.

**Comment by rezachalak** [comment]
I have the same problem with qemu-guest-agent can it be the same issue?

0d2dcdc851d37a8f3edd2e9382b0b1703b39d439ce9044541206281ecdc8339d

**Environment**
Talos version: 1.11.2
Kubernetes version: 1.33.0
Platform: Proxmox

**Comment by smira** [comment]
@rezachalak give us a full URL please of what you're trying to fetch from the Image Factory that returns 500.

**Comment by rezachalak** [comment]
The error has gone now, I'm not sure what was the issue with that, probably it was a temporary network issue, sorry...
Btw, here is the error log:
```
msg=fetch failed after status: 500 Internal Server Error host=factory.talos.dev
image=factory.talos.dev/nocloud-installer/0d2dcdc851d37a8f3edd2e9382b0b1703b39d439ce9044541206281ecdc8339d:v1.11
```

**Comment by smira** [comment]
In the URL you have wrong version. - there is no version "v1.11", you need "v1.11.2" for example.
